---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app-db
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/rajshivaram/spring-app-db-sample.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true
