apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-db
  template:
    metadata:
      labels:
        app: springboot-app-db
    spec:
      containers:
        - name: springboot-app-db
          image: rajshivaram7/springboot-app-db
          resources:
            requests:
              memory: 2048Mi
              cpu: "100m"
            limits:
              memory: 5981Mi
              cpu: "300m"
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: springdemo-postgres-connection
                  key: host
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(DB_HOST):5432/hsdp
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: springdemo-postgres-connection
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springdemo-postgres-connection
                  key: password
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64