apiVersion: v1
kind: Service
metadata:
  name: springboot-app-db-service
spec:
  selector:
    app: springboot-app-db
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9090
  type: ClusterIP
